// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrGiCBF4ucOFnubQ71ecDWl1ibEjFhVQ0',
    appId: '1:827752782201:web:fa07f7994d9f815bd2f7a8',
    messagingSenderId: '827752782201',
    projectId: 'dchakra-78845',
    authDomain: 'dchakra-78845.firebaseapp.com',
    storageBucket: 'dchakra-78845.firebasestorage.app',
    measurementId: 'G-01ZTXQWYXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8UeR78_UminImrCVTGjkKoU-D1ynzjpk',
    appId: '1:827752782201:android:5718cd6c52311adcd2f7a8',
    messagingSenderId: '827752782201',
    projectId: 'dchakra-78845',
    storageBucket: 'dchakra-78845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtZHrG8OZgaLtQ1-RMWEn9eLIeB3xj5gI',
    appId: '1:827752782201:ios:92c6c83cefdd74eed2f7a8',
    messagingSenderId: '827752782201',
    projectId: 'dchakra-78845',
    storageBucket: 'dchakra-78845.firebasestorage.app',
    iosBundleId: 'com.example.dchakra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtZHrG8OZgaLtQ1-RMWEn9eLIeB3xj5gI',
    appId: '1:827752782201:ios:92c6c83cefdd74eed2f7a8',
    messagingSenderId: '827752782201',
    projectId: 'dchakra-78845',
    storageBucket: 'dchakra-78845.firebasestorage.app',
    iosBundleId: 'com.example.dchakra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrGiCBF4ucOFnubQ71ecDWl1ibEjFhVQ0',
    appId: '1:827752782201:web:108a7d30506bb7a5d2f7a8',
    messagingSenderId: '827752782201',
    projectId: 'dchakra-78845',
    authDomain: 'dchakra-78845.firebaseapp.com',
    storageBucket: 'dchakra-78845.firebasestorage.app',
    measurementId: 'G-50YHCSL56M',
  );

}